version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: "fastapi_app"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis:6379/0"
    env_file:
      - .env
